site_name: nomad-simulation-parsers
site_description: A repository for housing NOMAD's collection of simulation parser plugins.
site_author: Joseph Rudzinski

repo_url: https://github.com/FAIRmat-NFDI/nomad-simulation-parsers
edit_uri: ""

nav:
  - Home: index.md
  # - Tutorial: tutorial/tutorial.md
  - How-to guides:
      - Install this Plugin: how_to/install_this_plugin.md
      - Use this Plugin: how_to/use_this_plugin.md
      - Contribute to this plugin: how_to/contribute_to_this_plugin.md
      - Contribute to the documentation: how_to/contribute_to_the_documentation.md
  - Parsers:
      - FHI-aims:
          - About: parsers/fhi-aims/fhi-aims_about.md
      - Gromacs:
          - About: parsers/gromacs/gromacs_about.md
      - H5MD:
          - About: parsers/h5md/h5md_about.md
          - How-to store data: parsers/h5md/h5md_howto.md
          - The H5MD Schema: parsers/h5md/h5md_expl.md
          - H5MD Reference: parsers/h5md/h5md_ref.md
      # - LAMMPS:
      #     - About: parsers/lammps/lammps_about.md
      - VASP:
          - About: parsers/vasp/vasp_about.md

  - Explanation:
      - Overview: explanation/explanation.md
      - Exchange-correlation functionals: explanation/xc-functionals.md
  - Reference:
      - General: reference/references.md
      - Parser file-mapping report: reference/parser_mapping_report.md
plugins:
  - search
theme:
  name: material
  palette:
    primary: "#2A4CDF"
    accent: "#008A67"
  font:
    text: "Titillium Web"
  logo: assets/nomad-plugin-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
  custom_dir: docs/theme
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - mkdocs-click
  - pymdownx.extra
extra:
  generator: false
  homepage: https://nomad-lab.eu
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
