#!/usr/bin/env bash
# Snapshot additivity check, runnable locally and in CI.
#
# Verifies that a `source` ref does not modify or drop archive data present in a
# `target` ref: it generates a parser-output JSON snapshot for each ref (from
# scratch, never committed) and compares them with compare_snapshots.py. Only
# purely additive changes pass.
#
#   Usage: tests/parsers/check_additivity.sh [target-ref] [source-ref] [parser ...]
#          target-ref  baseline whose data must not change   (default: develop)
#          source-ref  ref under test                        (default: HEAD)
#          parser...   parser directories to snapshot (e.g. `orca vasp`);
#                      default: autodetect from the target..source diff, falling
#                      back to all parsers on a shared/core change.
#
# A snapshot is generated by checking the ref out into a worktree and
# reinstalling the plugin from there with --no-deps, so that ref's code AND its
# matching entry points are used while the resolved dependencies (the pinned
# nomad-lab with deterministic ordering) are kept. This mutates the active venv,
# so the script restores the current checkout's editable install on exit.
#
# Generation is skipped for any ref whose output .json already exists, which lets
# CI restore them from a per-SHA cache. Override the output paths with the
# TARGET_JSON / SOURCE_JSON environment variables.
set -euo pipefail

TARGET_REF="${1:-develop}"
SOURCE_REF="${2:-HEAD}"
PARSERS="${*:3}"          # explicit parser selection (optional)

HERE="$(cd "$(dirname "$0")" && pwd)"          # tests/parsers
REPO="$(cd "$HERE/../.." && pwd)"
TARGET_JSON="${TARGET_JSON:-$REPO/target_snapshots.json}"
SOURCE_JSON="${SOURCE_JSON:-$REPO/source_snapshots.json}"

# Restore the checkout's own editable install when we are done swapping venvs.
trap 'uv pip install -e "$REPO" --no-deps >/dev/null 2>&1 || true' EXIT

resolve () {  # accept HEAD, a branch name, or a raw commit SHA
  if [ "$1" = 'HEAD' ]; then
    git -C "$REPO" rev-parse --verify HEAD
    return
  fi
  git -C "$REPO" fetch --quiet origin "$1" 2>/dev/null || true
  git -C "$REPO" rev-parse --verify --quiet "origin/$1" \
    || git -C "$REPO" rev-parse --verify "$1"
}

TARGET_SHA="$(resolve "$TARGET_REF")"
SOURCE_SHA="$(resolve "$SOURCE_REF")"

# Autodetect which parsers to snapshot when none are given explicitly.
if [ -z "$PARSERS" ]; then
  changed="$(git -C "$REPO" diff --name-only "$TARGET_SHA".."$SOURCE_SHA" || true)"
  if printf '%s\n' "$changed" | grep -Eq \
      '^(pyproject\.toml|uv\.lock|src/nomad_simulation_parsers/(schema_packages|parsers/utils|parsers/__init__\.py)|tests/parsers/(conftest\.py|common\.py|generate_snapshots\.py))'; then
    echo 'shared/core change -> snapshotting all parsers'
    PARSERS=''  # empty -> generate_snapshots.py snapshots every parser
  else
    PARSERS="$(printf '%s\n' "$changed" \
      | sed -n -E 's#^(src/nomad_simulation_parsers/parsers|tests/parsers)/([^/]+)/.*#\2#p' \
      | sort -u | tr '\n' ' ')"
    echo "autodetected changed parsers: ${PARSERS:-<none, snapshotting all>}"
  fi
fi

echo "comparing source ${SOURCE_REF} (${SOURCE_SHA}) against target ${TARGET_REF} (${TARGET_SHA})"

generate () {  # <sha> <out.json> <worktree-name>
  local sha="$1" out="$2" name="$3"
  if [ -f "$out" ]; then
    echo "reuse ${name} snapshot: ${out}"
    return
  fi
  local wt
  wt="$(mktemp -d)/snapshot-${name}"
  git -C "$REPO" worktree add --quiet --force "$wt" "$sha"
  cp "$HERE/generate_snapshots.py" "$wt/tests/parsers/"
  uv pip install -e "$wt" --no-deps >/dev/null
  # shellcheck disable=SC2086  # word-splitting of $PARSERS is intended
  ( cd "$wt" && python tests/parsers/generate_snapshots.py "$out" $PARSERS )
  git -C "$REPO" worktree remove --force "$wt"
}

generate "$TARGET_SHA" "$TARGET_JSON" target
generate "$SOURCE_SHA" "$SOURCE_JSON" source

python "$HERE/compare_snapshots.py" "$TARGET_JSON" "$SOURCE_JSON"
