#!/usr/bin/env bash
# Snapshot additivity check, runnable locally and in CI.
#
# Verifies that a `source` ref does not drop archive data present in a `target`
# ref: it generates a parser-output snapshot for each ref and compares them with
# compare_snapshots.py (the source must be a structural superset of the target).
#
#   Usage: tests/parsers/check_additivity.sh [target-ref] [source-ref]
#          target-ref  baseline whose data must not be lost   (default: develop)
#          source-ref  ref under test                          (default: HEAD)
#
# A snapshot is generated by checking the ref out into a worktree and reinstalling
# the plugin from there with `--no-deps`, so that ref's code AND its matching
# entry points are used while the resolved dependencies (the pinned nomad-lab with
# deterministic ordering) are kept. This mutates the active venv, so the script
# restores the current checkout's editable install on exit.
#
# Generation is skipped for any ref whose output .ambr already exists, which lets
# CI restore them from a per-SHA cache. Override the output paths with the
# TARGET_AMBR / SOURCE_AMBR environment variables.
set -euo pipefail

TARGET_REF="${1:-develop}"
SOURCE_REF="${2:-HEAD}"

HERE="$(cd "$(dirname "$0")" && pwd)"          # tests/parsers
REPO="$(cd "$HERE/../.." && pwd)"
TARGET_AMBR="${TARGET_AMBR:-$REPO/target_snapshots.ambr}"
SOURCE_AMBR="${SOURCE_AMBR:-$REPO/source_snapshots.ambr}"

# Restore the checkout's own editable install when we are done swapping venvs.
trap 'uv pip install -e "$REPO" --no-deps >/dev/null 2>&1 || true' EXIT

resolve () {  # accept HEAD, a branch name, or a raw commit SHA
  if [ "$1" = 'HEAD' ]; then
    git -C "$REPO" rev-parse --verify HEAD
    return
  fi
  git -C "$REPO" fetch --quiet origin "$1" 2>/dev/null || true
  git -C "$REPO" rev-parse --verify --quiet "origin/$1" \
    || git -C "$REPO" rev-parse --verify "$1"
}

generate () {  # <sha> <out.ambr> <worktree-name>
  local sha="$1" out="$2" name="$3"
  if [ -f "$out" ]; then
    echo "reuse ${name} snapshot: ${out}"
    return
  fi
  local wt
  wt="$(mktemp -d)/snapshot-${name}"
  git -C "$REPO" worktree add --quiet --force "$wt" "$sha"
  cp "$HERE/test_migration_snapshots.py" "$wt/tests/parsers/"
  mkdir -p "$wt/tests/parsers/__snapshots__"
  uv pip install -e "$wt" --no-deps >/dev/null
  ( cd "$wt" && python -m pytest --snapshot-update -q -p no:cacheprovider \
      tests/parsers/test_migration_snapshots.py )
  cp "$wt/tests/parsers/__snapshots__/test_migration_snapshots.ambr" "$out"
  git -C "$REPO" worktree remove --force "$wt"
}

TARGET_SHA="$(resolve "$TARGET_REF")"
SOURCE_SHA="$(resolve "$SOURCE_REF")"
echo "comparing source ${SOURCE_REF} (${SOURCE_SHA}) against target ${TARGET_REF} (${TARGET_SHA})"

generate "$TARGET_SHA" "$TARGET_AMBR" target
generate "$SOURCE_SHA" "$SOURCE_AMBR" source

python "$HERE/compare_snapshots.py" "$TARGET_AMBR" "$SOURCE_AMBR"
