#!/usr/bin/env bash
# Additive-output check, runnable locally and in CI (the additive-output-changes
# workflow calls this same script).
#
# Verifies that a `source` ref does not modify or drop archive data present in a
# `target` ref: it generates a parser-output JSON snapshot for each ref (from
# scratch, never committed) and compares them with compare_snapshots.py.
#
# Policy (three tiers per parser): `identical` passes silently, `additive`
# passes but is surfaced as a non-failing warning annotation under GitHub
# Actions, and a removed or changed leaf is a hard failure (exit 1, printing
# `old -> new`). A deliberate move or value change is meant to fail here; you
# review it by reading this local diff and confirming it is intended.
#
#   Usage: tests/parsers/check_additivity.sh [target-ref] [source-ref] [parser ...]
#          target-ref  baseline whose data must not change   (default: develop)
#          source-ref  ref under test                        (default: HEAD)
#          parser...   parser directories to snapshot (e.g. `orca vasp`);
#                      default: autodetect from the target..source diff, falling
#                      back to all parsers on a shared/core change.
#
# A snapshot is generated by checking the ref out into a worktree and running
# the generator with that worktree's src on PYTHONPATH, so the ref's own parser
# code is imported (it shadows the installed plugin) while the caller's
# already-resolved dependencies (the pinned nomad-lab with deterministic
# ordering) are reused. The caller's environment is never modified -- nothing is
# installed and nothing needs restoring.
#
# Generation is skipped for any ref whose output .json already exists, which lets
# CI restore them from a per-SHA cache. Override the output paths with the
# TARGET_JSON / SOURCE_JSON environment variables.
set -euo pipefail

TARGET_REF="${1:-develop}"
SOURCE_REF="${2:-HEAD}"
PARSERS="${*:3}"          # explicit parser selection (optional)

HERE="$(cd "$(dirname "$0")" && pwd)"          # tests/parsers
REPO="$(cd "$HERE/../.." && pwd)"
TARGET_JSON="${TARGET_JSON:-$REPO/target_snapshots.json}"
SOURCE_JSON="${SOURCE_JSON:-$REPO/source_snapshots.json}"

resolve () {  # accept HEAD, a branch name, or a raw commit SHA
  if [ "$1" = 'HEAD' ]; then
    git -C "$REPO" rev-parse --verify HEAD
    return
  fi
  git -C "$REPO" fetch --quiet origin "$1" 2>/dev/null || true
  git -C "$REPO" rev-parse --verify --quiet "origin/$1" \
    || git -C "$REPO" rev-parse --verify "$1"
}

TARGET_SHA="$(resolve "$TARGET_REF")"
SOURCE_SHA="$(resolve "$SOURCE_REF")"

# Autodetect which parsers to snapshot when none are given explicitly.
if [ -z "$PARSERS" ]; then
  changed="$(git -C "$REPO" diff --name-only "$TARGET_SHA".."$SOURCE_SHA" || true)"
  if printf '%s\n' "$changed" | grep -Eq \
      '^(pyproject\.toml|uv\.lock|src/nomad_simulation_parsers/(schema_packages|parsers/utils|parsers/__init__\.py)|tests/parsers/(conftest\.py|common\.py|generate_snapshots\.py))'; then
    echo 'shared/core change -> snapshotting all parsers'
    PARSERS=''  # empty -> generate_snapshots.py snapshots every parser
  else
    PARSERS="$(printf '%s\n' "$changed" \
      | sed -n -E 's#^(src/nomad_simulation_parsers/parsers|tests/parsers)/([^/]+)/.*#\2#p' \
      | sort -u | tr '\n' ' ')"
    echo "autodetected changed parsers: ${PARSERS:-<none, snapshotting all>}"
  fi
fi

echo "comparing source ${SOURCE_REF} (${SOURCE_SHA}) against target ${TARGET_REF} (${TARGET_SHA})"

generate () {  # <sha> <out.json> <worktree-name>
  local sha="$1" out="$2" name="$3"
  if [ -f "$out" ]; then
    echo "reuse ${name} snapshot: ${out}"
    return
  fi
  local tmp wt
  tmp="$(mktemp -d)"
  wt="$tmp/snapshot-${name}"       # git worktree add needs a non-existent path
  # Run inside a subshell whose EXIT trap always removes the worktree and temp
  # dir, so a failure mid-generation leaves nothing behind for the next run.
  (
    trap 'git -C "$REPO" worktree remove --force "$wt" 2>/dev/null || true; rm -rf "$tmp"' EXIT
    git -C "$REPO" worktree add --quiet --force "$wt" "$sha"
    cd "$wt"
    # Import the ref's own code via PYTHONPATH (shadowing the installed plugin)
    # while reusing the caller's resolved dependencies; nothing is installed and
    # the caller's environment is untouched. The generator itself comes from the
    # running checkout, so the target ref need not carry this tooling.
    # shellcheck disable=SC2086  # word-splitting of $PARSERS is intended
    PYTHONPATH="$wt/src" python "$HERE/generate_snapshots.py" "$out" $PARSERS
  )
}

generate "$TARGET_SHA" "$TARGET_JSON" target
generate "$SOURCE_SHA" "$SOURCE_JSON" source

python "$HERE/compare_snapshots.py" "$TARGET_JSON" "$SOURCE_JSON"
